Update of making cleaner code and organized files
Code-the-Dream-School/ee-prac-team1-back pull request #6
Opened 2023-11-15 22:53 UTC by Ljanjic

Based on Vitali's feedback, did a better organization to improve the readability of our back-end code, by destructuring code in controllers and routes files, creating Auth(Register, Login, Logout), User(edit User Profile, Delete User account), and Activity (routes)files

2023-11-16 01:24 UTC, vitaliipp requested changes
Great job overall. Please split pull requests into small parts as much as you can. Don't forget to pull the main branch to avoid merging conflicts.

2023-11-16 01:24 UTC, vitaliipp commented on src/controllers/activityController.js
> +    console.error('Error in getActivity:', error);
Please remove lines:
36 user: { userId },
41 createdBy: userId,
getActivity should be unprotected

2023-11-16 01:24 UTC, vitaliipp commented on src/app.js
> +app.use('/api/v1/auth/users', userRouter);
Should be app.use('/api/v1/users', userRouter);

2023-11-17 14:34 UTC, vitaliipp approved these changes
Looks good to me

2023-11-19 01:17 UTC, benochi approved these changes

2023-11-19 01:17 UTC, merged